<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadRepository extends \AppBundle\Libs\Repository\BaseRepository
{
    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR)
    {

    }

    public function verifyExistance($nombre = '', $id = -1)
    {
        $qb = $this->createQueryBuilder('esp');

        $exp = $qb->expr()->eq($qb->expr()->lower('esp.nombre'), '?1');
        $qb->setParameter(1, strtolower($nombre));

        $qb->where($exp);

        if ($id != -1) {
            $qb->andWhere($qb->expr()->neq('esp.id', '?2'));
            $qb->setParameter(2, $id);
        }
        $result = $qb->getQuery()->getResult();
        if (count($result) > 0) {
            return true;
        } else {
            return false;
        }
    }
}