<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ResultQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolucionRepository extends \AppBundle\Libs\Repository\BaseRepository
{
    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR)
    {

    }

    public function getAllEvolutionsByPattient($query, $idEv =null)
    {
        $qb = $this->createQueryBuilder('ev');
        $qb->join('ev.consulta', 'query');
        $qb->join('query.usuarioRegistro', 'usuarioRegistro');
        $qb->andWhere($qb->expr()->eq('usuarioRegistro', '?1'));
        $qb->setParameter(1, $query->getUsuarioRegistro()->getId());

        $qb->addOrderBy('query.anno','DESC');
        $qb->addOrderBy('query.mes','DESC');
        $qb->addOrderBy('query.dia','DESC');
        $qb->addOrderBy('query.horaFinal','DESC');
        $qb->addOrderBy('query.horaInicial','DESC');
        $qb->addOrderBy('query.minutoFinal','DESC');
        $qb->addOrderBy('query.minutoInicial','DESC');

        $qb->andWhere($qb->expr()->lte('query.dia', ($query->getDia())));
        $qb->andWhere($qb->expr()->lte('query.mes', ($query->getMes())));
        $qb->andWhere($qb->expr()->lte('query.anno', ($query->getAnno())));
        if ($idEv != null) {
            $qb->andWhere($qb->expr()->neq('ev.id', ($idEv)));
        }
        return $qb->getQuery()->getResult();
    }
}