<?php

namespace AppBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \AppBundle\Libs\Repository\BaseRepository
{

    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR)
    {

    }

    public function getUserAdminOrSecretary()
    {
        $qb = $this->createQueryBuilder('user');
        $qb->join('user.rol', 'rol');
        $qb->where($qb->expr()->eq('rol', 3));
        $qb->orWhere($qb->expr()->eq('rol', 4));
        return $qb->getQuery()->getResult();
    }

    public function verifyExistance($userName = '', $id = -1)
    {
        $qb = $this->createQueryBuilder('user');

        $exp = $qb->expr()->eq($qb->expr()->lower('user.nombreUsuario'), '?1');
        $qb->setParameter(1, strtolower($userName));

        $qb->where($exp);

        if ($id != -1) {
            $qb->andWhere($qb->expr()->neq('user.id', '?2'));
            $qb->setParameter(2, $id);
        }
        $result = $qb->getQuery()->getResult();
        if (count($result) > 0) {
            return true;
        } else {
            return false;
        }
    }


}
