security:
    # para que invalide la sesion si no da problemas cuando inicia sessio que no deja entrar
    #probar quitar erase_credentials a ver si se mantiene bien
    encoders:
       AppBundle\Entity\Usuario:
         algorithm: sha512
         encode_as_base64: false
         iterations: 10
            

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: AppBundle\Entity\Usuario, property: nombreUsuario }


    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js|img)
                security: false

            login:
                pattern:  /manage/login?$
                security: false

            secured_area:
                pattern:    ^/manage
                form_login:
                    check_path: /manage/login_check
                    login_path: /manage/login
                    post_only: true
                    default_target_path: /manage
                    success_handler: my.security.login_handler
                    #require_previous_session: false

                logout:
                    path:   /manage/logout
                    target: /manage/login

    access_control:
            - { path: ^/manage/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
            - { path: ^/manage, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }